---
- name: Install and configure Nginx web server
  hosts: webservers
  become: yes
  tasks:

    - name: Install Nginx
      ansible.builtin.yum:
        name: nginx
        state: present

    - name: Ensure Nginx service is running
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: Create a simple index.html
      ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: "<h1>Welcome to Ansible-managed Nginx!</h1>"
        owner: root
        group: root
        mode: '0644'
